# Conclusion

The aim of this Master's Thesis was not to create 'yet another tool' (YAT), but to build upon the experience of the previous studies and incorporate their knowledge. Without reproducibility it is hard to really understand and recreate workflows, thus a reproducible workflow like the one developed in this Master’s thesis can facilitate the understanding and utilization of automated analysis also by less technically trained archaeologists. It can also enable the advancement by other specialists and also to recycle parts of the workflow and gained knowledge. 
The archaeological significance of such a reproducible workflow is moreover the assistance in the analysis of archaeologically big data sets and not only research purposes are targeted but moreover the Cultural Heritage Management sector. The post-processing of the results shows, that the human operator cannot be removed from the equation in a semi-automated analysis, who has an integral part in providing the variable settings for the different functions in the workflow and by choosing the reference data (extracted from reference mounds) which can be also generalized (an artificial threshold range), but the different amount of input data (number of tiles) calls for different variable settings which frequently have to be checked. 
Breaking the **iSEGmound** down to it's elements, it can be said, that a ***Multi-Sclae Topografic Index*** derivative, the result of **iMound** and the result of the **Watershed Segmentation** hold their own ground even as separate methods.
A ***Multi-Sclae Topografic Index*** enhances Objects of Interest on multiple levels and the resulting integral image (the **SAGA and the Whitebox version**) is a better option than a **Local Relief Model**, which enhances the micro-topography and thus also the artifacts of the spatial interpolation of the ground points.
\newline
**iMound**, as a method can basically reduce the amount of data to be inspected when looking for Objects of Interest which protrude enough from the ground. Thus **iMound** could be used as a useful data extraction method as data preparation in projects with big areas to cover.
\newline
**GeOBIA algorithms** treat Objects of Interest as integral object and not as pixels and thus deliver more accurate results.
\newline
**iSEGmound** was applied on an area where previous information was known about the Objects of Interest and made use of the benefits of all the methods together. All three sub-methods can be (for better result have to be set because of the scale-dependency of the Areas of Interest) set independently and the method can also be used without a setting thresholds or setting different thresholds with different shape descriptors for different Objects of interest.
\newline
This thesis showed that it is not only possible to reuse existing (legacy) data sets but also to reuse existing knowledge not only about automated analysis but also archaeological knowledge: regional topographical studies can be revisited and **iSEGmound** can function as change detection. 
This method has of course it's flows and many aspects still have to be tested and understood, but it can be a useful tool, when presented with a baseline. 

