---
title: "iSEGMound – a Reproducible Workflow for Mound Detection in LiDAR-derived DTMs"
subtitle: "Agnes Schneider"
author: 
- "Submitted in accordance with the requirements for the degree of Master of Science"
- "Philipps-University Marburg" 
- "Department of Physical Geography"

site: bookdown::bookdown_site

date: '16.09.2021'
output: 
    bookdown::pdf_book:
      df_print: kable
      latex_engine: lualatex
      fig_caption: yes
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
      fontsize: 12pt
      toc: true
      toc-depth: 5
      number_sections: true
bibliography: "../templates/references.bib"
csl: "../templates/antiquity.csl" # Insert path for the bib-style
always_allow_html: true   

---
\newpage
```{r child = here::here("analysis", "thesis", "01-Intro.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "02-Literature.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "03-Materials.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "04-Methods.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "05-Results.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "06-Discussion.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "07-Conclusion.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "08-Bibliography.Rmd")}
```
\newpage
```{r child = here::here("analysis", "thesis", "09-Colophon.Rmd")}
```
